### PR TITLE
Update users and channels tables on duplicate

### PR DESCRIPTION
**Pull request by asafalima**

### CODE REVIEW

**Comment by asafalima** [comment]
@JarredOlson Can you please review this?

**Comment by JarredOlson** [comment]
@asafalima sorry for the slow response.  If you would still like to get this merged in could you please resolve some of the newly introduced conflicts, and ensure that this is currently working with the latest version of botkit?

**Comment by asafalima** [comment]
@JarredOlson Thanks for your response, my branch is now updated from master and I verified that everything still works with botkit 0.6.16 (according to the change log there're no changes to the storage api).

**Comment by JarredOlson** [comment]
@asafalima Merged and released.  Thanks for your assistance, and please validate 1.0.5 is working whenever you have a chance.

**Pull request merged**
